# Generated by Django 4.0 on 2024-09-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=20)),
                ('empname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('joined_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
